apiVersion: v1
kind: Service
metadata:
  name: web88
  labels:
    app: web88
spec:
  type: NodePort
  selector:
    app: web88
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32088   # BEST PRACTICE: app name in the port

