apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: web-gateway-1
  namespace: dev-test
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
